### ISSUE TITLE
unable to merge or commit

### ISSUE THREAD

**Issue by akashdeepsingh9988** [pH-7/Simple-Java-Text-Editor#10]
I added new font features to the text editor, but i am unable to merge files or adding pull request

**Comment by pH-7** [comment]
Hi Akashdeep,

Your branch isn't up-to-date. I added a few cleanup commits after yours so you need to update your current branch first to get those older commits first.

Try to to:
`git fetch`
`git pull origin master`

You might have some minor conflicts to fix after that.


Hope this helps

**Comment by akashdeepsingh9988** [comment]
Thank you
