### ISSUE TITLE
keywords highlighting

### ISSUE THREAD

**Issue by shaoye** [pH-7/Simple-Java-Text-Editor#12]
`AutoComplete` is awesome!

But I wonder how to implement the highlighting effect for the `SupportKeywords`? 

Can you add this effect?

**Comment by ghost** [comment]
I find this and i will try to include it in this editor:
https://bitsbyta.blogspot.fr/2011/04/highlighting-text-in-jtextarea-java.html

Edit : this solution works for me. I will take a moment to propose a merge request.

**Comment by pH-7** [comment]
👍  Thanks a lot for that!! I will review it!

**Comment by pH-7** [comment]
> I find this and i will try to include it in this editor:
> https://bitsbyta.blogspot.fr/2011/04/highlighting-text-in-jtextarea-java.html
> 
> Edit : this solution works for me. I will take a moment to propose a merge request.

Hey @ehermellin 
Hope you are still doing well so far 😊

It might sound odd to get back to you after so long, but I was reviewing all issues posted on this project and realized I haven't heard from you about the solution that was working for you. Do you still have it?

Thank you!
