### ISSUE TITLE
Autocomplete when open file and Editor title

### ISSUE THREAD

**Issue by ghost** [pH-7/Simple-Java-Text-Editor#14]
When opening a file (.java, .cpp), autocomplete doesn't work and the title of the editor doesn't change. 

For the editor NAME the line behind could be added in the open actionlistener or a method could be created to avoid duplicate source code.
 
https://github.com/pH-7/Simple-Java-Text-Editor/blob/5ea87f86c468e2c4a8011a606e1c1e482fbadd10/src/simplejavatexteditor/UI.java#L423

For autocomplete option, line 434 to 468 could be added in the open actionlistener. Once again a method could be created to avoid duplicate source code.

I will propose a merge request if i find time to make these modifications

Best regards, 

Emmanuel.

**Comment by pH-7** [comment]
If I'm not wrong, this patch will fix the issue https://github.com/pH-7/Simple-Java-Text-Editor/issues/14
So, I'm already closing this issue. 
@ehermellin Thanks a lot for mentioning it! HIGHLY Appreciate!
