### ISSUE TITLE
I did some improvements

### ISSUE THREAD

**Issue by frangametv** [pH-7/Simple-Java-Text-Editor#42]
[Notepad.zip](https://github.com/pH-7/Simple-Java-Text-Editor/files/8793220/Notepad.zip)

**Comment by pH-7** [comment]
Amazing!

- What changes have you done? 
- What improvements?
Could you raise a pull request on the changes you have done? This is the only way to accept your changes. 


Thank you!


Have a great day!

**Comment by frangametv** [comment]
Ok, i did it
