### ISSUE TITLE
Any way to use word wrap?

### ISSUE THREAD

**Issue by 2braincells2go** [pH-7/Simple-Java-Text-Editor#7]
Nice little notepad!

Cannot seem to figure out way to use "word wrap" or get scroll-bars to appear. Any ideas on solution?

Thanks!

**Comment by akashdeepsingh9988** [comment]
To use word wrap add a menu item in edit or any other menu and set action on the menuitem.  
Add the following line to wrap text 

`textArea.setLineWrap(true);`

**Comment by 2braincells2go** [comment]
Thanks

**Comment by pH-7** [comment]
Thanks @akashdeepsingh9988 for your help here 👍  Might implement that if I have time

**Comment by pH-7** [comment]
Implemented thanks @akashdeepsingh9988 
Close by now
